=== soltys/OpenRem/Software/BL/OpenRem.Config/ConfigFiles/AnalyzerConfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="AnalyzerConfig"
    targetNamespace="https://github.com/soltys/OpenRem/AnalyzerConfig.xsd"
    elementFormDefault="qualified"
    xmlns="https://github.com/soltys/OpenRem/AnalyzerConfig.xsd"
    xmlns:tns="https://github.com/soltys/OpenRem/AnalyzerConfig.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="AnalyzerList" type="tns:AnalyzerList"/>

  <xs:complexType name="AnalyzerList">
    <xs:sequence>
      <xs:element name="Analyzer" maxOccurs="unbounded" type="tns:Analyzer"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Analyzer">
    <xs:sequence>
      <xs:element name="Name" type="xs:string"/>
      <xs:element name="SampleRate" type="xs:positiveInteger"/>
      <xs:element name="SubChunkSize" type="xs:positiveInteger"/>
      <xs:element name="ChannelsNumber" type="xs:positiveInteger"/>
      <xs:element name="Probe" minOccurs="1" maxOccurs="2" type="tns:Probe">
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Probe">
    <xs:sequence>
      <xs:element name="Input" type="tns:Microphone"/>
      <xs:element name="Output" type="tns:Microphone"/>
    </xs:sequence>
    <xs:attribute name="Side">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Left"/>
          <xs:enumeration value="Right"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="Microphone">
    <xs:attribute name="Channel">
      <xs:simpleType>
        <xs:restriction base="xs:integer">
          <xs:minInclusive value="0"/>
          <xs:maxInclusive value="3"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
</xs:schema>

=== soltys/OpenRem/Software/BL/OpenRem.Config/ConfigFiles/AnalyzerConfig.xml
<?xml version="1.0" encoding="utf-8" ?>
<AnalyzerList
  xmlns="https://github.com/soltys/OpenRem/AnalyzerConfig.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://github.com/soltys/OpenRem AnalyzerConfig.xsd">
  <Analyzer>
    <Name>MKRZERO</Name>
    <SampleRate>44100</SampleRate>
    <BitRate>32</BitRate>
    <ChannelsNumber>2</ChannelsNumber>
    <Probe Side="Left">
      <Input Channel="0"/>
      <Output Channel="1"/>
    </Probe>
  </Analyzer>
  <Analyzer>
    <Name>Emulator</Name>
    <SampleRate>44100</SampleRate>
    <BitRate>32</BitRate>
    <ChannelsNumber>2</ChannelsNumber>
    <Probe Side="Left">
      <Input Channel="0"/>
      <Output Channel="1"/>
    </Probe>
  </Analyzer>
</AnalyzerList>
